version: '3.8'

services:
  neo4j:
    image: neo4j:5.14.0
    container_name: neo4j
    volumes:
      - neo4j-data:/data
    environment:
      - "NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-langchain-neo4j-advanced-rag-docker}"
      - "NEO4J_PLUGINS=[\"apoc\"]"
    networks:
      - langchain-neo4j-advanced-rag-docker
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    restart: always

  neo4j-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neo4j-init
    environment:
      - "OPENAI_API_KEY=${OPENAI_API_KEY:?}"
      - "NEO4J_URI=bolt://neo4j:7687"
      - "NEO4J_USERNAME=neo4j"
      - "NEO4J_PASSWORD=${NEO4J_PASSWORD:-langchain-neo4j-advanced-rag-docker}"
      - "LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY-placeholder}"
      - "LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}"
      - "LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-langchain-neo4j-advanced-rag-docker}"
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - langchain-neo4j-advanced-rag-docker
    command: ["/bin/bash", "/home/appuser/neo4j-advanced-rag/ingest.sh"]

  langchain-neo4j-advanced-rag-docker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langchain-neo4j-advanced-rag-docker
    environment:
      - "OPENAI_API_KEY=${OPENAI_API_KEY:?}"
      - "NEO4J_URI=bolt://neo4j:7687"
      - "NEO4J_USERNAME=neo4j"
      - "NEO4J_PASSWORD=${NEO4J_PASSWORD:-langchain-neo4j-advanced-rag-docker}"
      - "LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY-placeholder}"
      - "LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}"
      - "LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-langchain-neo4j-advanced-rag-docker}"
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      neo4j:
        condition: service_healthy
      neo4j-init:
        condition: service_completed_successfully
    networks:
      - langchain-neo4j-advanced-rag-docker

volumes:
  neo4j-data:

networks:
  langchain-neo4j-advanced-rag-docker:
    driver: bridge
